steps:
  - label: "CUDA Julia v{{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-test#v1:
          test_args: "--gpu"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  # - label: "AMDGPU Julia v{{matrix.version}}"
  #   matrix:
  #     setup:
  #       version:
  #         - "1.10"
  #   plugins:
  #     - JuliaCI/julia#v1:
  #         version: "{{matrix.version}}"
  #     - JuliaCI/julia-test#v1:
  #         test_args: "--gpu"
  #     - JuliaCI/julia-coverage#v1:
  #         codecov: true
  #         dirs:
  #           - src
  #           - ext
  #   agents:
  #     queue: "juliagpu"
  #     rocm: "*"
  #   if: build.message !~ /\[skip tests\]/
  #   timeout_in_minutes: 60

  # - label: "Metal Julia v{{matrix.version}}"
  #   matrix:
  #     setup:
  #       version:
  #         - "1.8"
  #         - "1.9"
  #   plugins:
  #     - JuliaCI/julia#v1:
  #         version: "{{matrix.version}}"
  #   agents:
  #     queue: "juliaecosystem"
  #     os: "macos"
  #     arch: "aarch64"
  #   if: build.message !~ /\[skip tests\]/
  #   timeout_in_minutes: 60
  #   commands: |
  #     echo "--- Setup Julia packages"
  #     julia --color=yes -e '
  #         import Pkg
  #         Pkg.develop(; path = pwd())
  #         Pkg.develop(; path = joinpath(pwd(), "lib", "EnzymeCore"))
  #         Pkg.develop(; name = "Metal")' || exit 3

  #     echo "+++ Run tests"
  #     julia --color=yes test/metal.jl
  #   env:
  #     JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
