# Auto-generated file - DO NOT EDIT
# Generated by make-proto-bindings.jl from bazel-staged proto files
#
# This module provides Julia bindings for XLA/TSL proto messages.
# Regenerate with:
#   cd deps/ReactantExtra
#   julia --project=. make-proto-bindings.jl --force

module Proto

using ProtoBuf

# Generated proto bindings
include("google/google.jl")
include("stream_executor/stream_executor.jl")
include("tensorflow/tensorflow.jl")
include("tsl/tsl.jl")
include("xla/xla.jl")
include("xla_autotuning/xla_autotuning.jl")
include("xla_tsl_dnn/xla_tsl_dnn.jl")

end # module Proto
