#!/usr/bin/env julia
"""
Script to create a TODO-to-issue mapping based on created GitHub issues.

This script reads:
1. scripts/todo_mapping_template.csv (generated by categorize_todos.jl)
2. scripts/created_issues.csv (generated by create_github_issues.sh)

And produces:
- scripts/todo_mapping.csv (ready to use with update_todos.jl)

Usage:
    julia scripts/map_todos_to_issues.jl
"""

function main()
    root_dir = dirname(dirname(@__FILE__))
    scripts_dir = joinpath(root_dir, "scripts")
    
    # Check prerequisites
    template_file = joinpath(scripts_dir, "todo_mapping_template.csv")
    issues_file = joinpath(scripts_dir, "created_issues.csv")
    
    if !isfile(template_file)
        error("Template file not found: $template_file\nRun: julia scripts/categorize_todos.jl")
    end
    
    if !isfile(issues_file)
        error("Created issues file not found: $issues_file\nRun: bash scripts/create_github_issues.sh")
    end
    
    # Read the created issues mapping (category -> issue_number)
    category_to_issue = Dict{String, String}()
    
    for line in readlines(issues_file)[2:end]  # Skip header
        if isempty(strip(line))
            continue
        end
        parts = split(line, ',')
        if length(parts) >= 2
            category = strip(parts[1], '"')
            issue_num = strip(parts[2])
            category_to_issue[category] = issue_num
        end
    end
    
    println("Loaded $(length(category_to_issue)) category mappings")
    
    # Read the template and fill in issue numbers
    output_file = joinpath(scripts_dir, "todo_mapping.csv")
    output_lines = String[]
    
    lines = readlines(template_file)
    push!(output_lines, lines[1])  # Header
    
    mapped_count = 0
    unmapped_count = 0
    
    for line in lines[2:end]
        if isempty(strip(line))
            continue
        end
        
        parts = split(line, ',')
        if length(parts) >= 3
            todo_id = strip(parts[1])
            category = strip(parts[3], '"')
            
            if haskey(category_to_issue, category)
                issue_num = category_to_issue[category]
                push!(output_lines, "$todo_id,$issue_num,\"$category\"")
                mapped_count += 1
            else
                # Keep line as-is (no issue number)
                push!(output_lines, line)
                unmapped_count += 1
                @warn "No issue mapping for category: $category"
            end
        end
    end
    
    # Write output
    open(output_file, "w") do io
        for line in output_lines
            println(io, line)
        end
    end
    
    println("\nSummary:")
    println("  Mapped: $mapped_count TODOs")
    println("  Unmapped: $unmapped_count TODOs")
    println("  Output: $output_file")
    println("\nNext step:")
    println("  julia scripts/update_todos.jl $output_file")
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
