import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Backend


@enumx Backend UNSPECIFIED_BACKEND=0 CUDNN=1 TRITON=2 CUBLAS=3 CUBLASLT=4 ROCBLAS=5 HIPBLASLT=6 MIOPEN=7 CUSTOM_KERNEL=8 BLOCK_LEVEL_EMITTER=9 NATIVE_EMITTER=10 LLVM_KERNEL_EMITTER=11 CUBLAS_FISSION=12 CUBLASLT_FISSION=13 CUSTOM_KERNEL_FISSION=14 ROCBLAS_FISSION=15
