name: CI

on:
  pull_request:
    paths: &paths
      - ".github/workflows/CI.yml"
      - ".github/workflows/CommonCI.yml"
      - "ext/**"
      - "lib/**"
      - "src/**"
      - "test/**"
      - "Project.toml"
  push:
    branches:
      - main
      - release-*
    tags: ["*"]
    paths: *paths

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.11"
        os:
          - linux-x86-ct6e-180-4tpu
        test_group:
          - probprog
        runtime:
          - "ifrt"
    uses: ./.github/workflows/CommonCI.yml
    with:
      julia_version: ${{ matrix.version }}
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}
      test_args: ${{ matrix.test_group == 'core' && 'core plugins' || matrix.test_group }}
