name: Bazel files check

on: [push]

jobs:
  formatting-check:
    name: Formatting Bazel files check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup buildifier
      uses: jbajic/setup-buildifier@v1

    - name: Run buildifier
      run: |
        buildifier -mode check -r .
