name: Bazel files auto format

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  formatting-check:
    name: Formatting Bazel files check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup buildifier
      uses: jbajic/setup-buildifier@v1

    - name: Run buildifier
      run: |
        buildifier -r .

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Format code
        title: 'Format code of branch "main"'
        branch: format-main
        delete-branch: true
        labels: format
        author: enzyme-ci-bot[bot] <78882869+enzyme-ci-bot[bot]@users.noreply.github.com>

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
