name: Integration

on:
  pull_request:
    paths:
      - ".github/workflows/Integration.yml"
      - "ext/**"
      - "lib/**"
      - "src/**"
      - "test/**"
      - "Project.toml"
  push:
    branches:
      - main
      - release-*
    tags: ["*"]
    paths:
      - ".github/workflows/Integration.yml"
      - "ext/**"
      - "lib/**"
      - "src/**"
      - "test/**"
      - "Project.toml"

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        project:
          - CUDA
          - FancyArrayTypes
          - FFT
          - Flux
          - Lux
          - NNlib
          - Python
        version:
          - "1.10"
          - "1.11"
        os:
          - ubuntu-latest
          - linux-x86-ct6e-180-4tpu
    uses: ./.github/workflows/CommonCI.yml
    with:
      julia_version: ${{ matrix.version }}
      os: ${{ matrix.os }}
      runtime: "both"
      project: "test/integration/${{ matrix.project }}"
